sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - npm run build-prod
before_deploy:
  - npm i now@1.0.0 --no-save
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - npm run alias
  - npm run clean-deploys
env:
  matrix:
    - INSTANCE_NAME='tapa-ole'
